controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    # diff_cont:
    #   type: diff_drive_controller/DiffDriveController

    # joint_broad:
    #   type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_cont:
      type: ackermann_steering_controller/AckermannSteeringController

    # joint_traj:
    #   type: joint_trajectory_controller/JointTrajectoryController


ackermann_cont:
  ros__parameters:
    publish_rate: 30.0

    # joints:
    #   - left_steer_joint
    #   - right_steer_joint

    # # interface_name: hardware_interface::PositionJointInterface
    # interface_name: position
    # command_interfaces:
    #   - position
    # state_interfaces:
    #   - position
    #   - velocity

    base_frame_id: base_link
    odom_frame_id: odom

    front_steering: true
    enable_odom_tf: true
    velocity_rolling_window_size: 10

    
    rear_wheels_names: ['left_wheel_joint', 'left_steer_joint']       # NEWLY ADDED
    front_wheels_names: ['right_wheel_joint', 'right_steer_joint']    # left_steer_joint

    wheel_separation: 0.242
    wheel_radius: 0.033


    use_stamped_vel: true

##############################################
# joint_traj:
#   ros__parameters:
#     joint_names:
#       # - left_wheel_joint
#       # - right_wheel_joint
#       - leftiii_wheel_joint
#       - rightiii_wheel_joint
#     interface_name: position
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity
#     # joint_names:
#     #   - left_wheel_joint
#     #   - right_wheel_joint
#     #   - leftiii_wheel_joint
#     #   - rightiii_wheel_joint
#     #   - left_steer_joint
#     #   - right_steer_joint



##############################################
# diff_cont:
#   ros__parameters:
#     publish_rate: 30.0

#     base_frame_id: base_link

#     left_wheel_names: ['left_wheel_joint', 'leftiii_wheel_joint']
#     right_wheel_names: ['right_wheel_joint', 'rightiii_wheel_joint']
#     wheel_separation: 0.242
#     wheel_radius: 0.033

#     use_stamped_vel: false
###############################################
# diff_cont:
#   ros__parameters:
#     publish_rate: 30.0

#     base_frame_id: base_link

#     left_wheel_names: ["left_wheel_joint"]
#     right_wheel_names: ["right_wheel_joint"]
#     wheel_separation: 0.242
#     wheel_radius: 0.033

#     use_stamped_vel: false

################################################


    # pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]    # NEWLY ADDED
    # twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    # open_loop: false

    # wheels_per_side: x
    # wheel_separation_multiplier: x
    # left_wheel_radius_multiplier: x
    # right_wheel_radius_multiplier: x

    # odom_frame_id: x
    # pose_covariance_diagonal: x
    # twist_covariance_diagonal: x
    # open_loop: x
    # enable_odom_tf: x

    # cmd_vel_timeout: x
    # publish_limited_velocity: x
    # velocity_rolling_window_size: x

    # linear.x.has_velocity_limits: false
    # linear.x.has_acceleration_limits: false
    # linear.x.has_jerk_limits: false
    # linear.x.max_velocity: NAN
    # linear.x.min_velocity: NAN
    # linear.x.max_acceleration: NAN
    # linear.x.min_acceleration: NAN
    # linear.x.max_jerk: NAN
    # linear.x.min_jerk: NAN

    # angular.z.has_velocity_limits: false
    # angular.z.has_acceleration_limits: false
    # angular.z.has_jerk_limits: false
    # angular.z.max_velocity: NAN
    # angular.z.min_velocity: NAN
    # angular.z.max_acceleration: NAN
    # angular.z.min_acceleration: NAN
    # angular.z.max_jerk: NAN
    # angular.z.min_jerk: NAN
# joint_broad:
#   ros__parameters: